/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.patolli.vistas;

/**
 *
 * @author Kevin Rios
 */
public class GuiConfigurarPartida extends javax.swing.JFrame {

    /**
     * Creates new form GuiConfigurarPartida
     */
    public GuiConfigurarPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfigurarPartida = new javax.swing.JLabel();
        comboJugadores = new javax.swing.JComboBox<>();
        lblJugadores = new javax.swing.JLabel();
        comboAspas = new javax.swing.JComboBox<>();
        lblCasillas = new javax.swing.JLabel();
        comboFichas = new javax.swing.JComboBox<>();
        lblFichas = new javax.swing.JLabel();
        lblFichas1 = new javax.swing.JLabel();
        lblFichas2 = new javax.swing.JLabel();
        txtFondo = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConfigurarPartida.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblConfigurarPartida.setText("Configurar Partida");

        comboJugadores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        comboJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJugadoresActionPerformed(evt);
            }
        });

        lblJugadores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblJugadores.setText("Jugadores");

        comboAspas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboAspas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        comboAspas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAspasActionPerformed(evt);
            }
        });

        lblCasillas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCasillas.setText("Casillas por aspa");

        comboFichas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6" }));
        comboFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFichasActionPerformed(evt);
            }
        });

        lblFichas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFichas.setText("Fichas por jugador");

        lblFichas1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFichas1.setText("Fondo de apuesta");

        lblFichas2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFichas2.setText("Monto por apuesta");

        txtFondo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtMonto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnContinuar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnContinuar.setText("Continuar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConfigurarPartida)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContinuar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFichas, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCasillas, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFichas1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFichas2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblJugadores, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboJugadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboAspas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboFichas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFondo, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfigurarPartida)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAspas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCasillas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFichas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFichas1)
                    .addComponent(txtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFichas2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnCancelar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJugadoresActionPerformed

    private void comboAspasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAspasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAspasActionPerformed

    private void comboFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFichasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFichasActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiConfigurarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> comboAspas;
    private javax.swing.JComboBox<String> comboFichas;
    private javax.swing.JComboBox<String> comboJugadores;
    private javax.swing.JLabel lblCasillas;
    private javax.swing.JLabel lblConfigurarPartida;
    private javax.swing.JLabel lblFichas;
    private javax.swing.JLabel lblFichas1;
    private javax.swing.JLabel lblFichas2;
    private javax.swing.JLabel lblJugadores;
    private javax.swing.JTextField txtFondo;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
