/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.patolli.vistas;

import mx.patolli.utils.ProtocoloMensaje;

import mx.patolli.control.ControlCliente;
import mx.patolli.dominio.Partida;

/**
 *
 * @author Kevin Rios
 */
public class GuiConfigurarPartida extends Gui {
    private ControlCliente control;
    /**
     * Creates new form GuiConfigurarPartida
     */
    public GuiConfigurarPartida(ControlCliente control) {
        initComponents();
        this.control=control;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboJugadores = new javax.swing.JComboBox<>();
        lblJugadores = new javax.swing.JLabel();
        comboAspas = new javax.swing.JComboBox<>();
        lblCasillas = new javax.swing.JLabel();
        txtFondo = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        comboFichas = new javax.swing.JComboBox<>();
        lblFichas = new javax.swing.JLabel();
        lblFichas1 = new javax.swing.JLabel();
        lblFichas2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Partida");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        comboJugadores.setBackground(new java.awt.Color(102, 102, 102));
        comboJugadores.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        comboJugadores.setForeground(new java.awt.Color(255, 255, 255));
        comboJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        comboJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJugadoresActionPerformed(evt);
            }
        });

        lblJugadores.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblJugadores.setText("Jugadores");

        comboAspas.setBackground(new java.awt.Color(102, 102, 102));
        comboAspas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        comboAspas.setForeground(new java.awt.Color(255, 255, 255));
        comboAspas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14" }));
        comboAspas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAspasActionPerformed(evt);
            }
        });

        lblCasillas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCasillas.setForeground(new java.awt.Color(255, 255, 255));
        lblCasillas.setText("Casillas por aspa");

        txtFondo.setBackground(new java.awt.Color(102, 102, 102));
        txtFondo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFondo.setForeground(new java.awt.Color(255, 255, 255));
        txtFondo.setText("0");

        txtMonto.setBackground(new java.awt.Color(102, 102, 102));
        txtMonto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(255, 255, 255));
        txtMonto.setText("0");
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        comboFichas.setBackground(new java.awt.Color(102, 102, 102));
        comboFichas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        comboFichas.setForeground(new java.awt.Color(255, 255, 255));
        comboFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        comboFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFichasActionPerformed(evt);
            }
        });

        lblFichas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblFichas.setForeground(new java.awt.Color(255, 255, 255));
        lblFichas.setText("Fichas por jugador");

        lblFichas1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblFichas1.setForeground(new java.awt.Color(255, 255, 255));
        lblFichas1.setText("Fondo de apuesta");

        lblFichas2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblFichas2.setForeground(new java.awt.Color(255, 255, 255));
        lblFichas2.setText("Monto por apuesta");

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(102, 102, 102));
        btnContinuar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/patolli/imagenes/tituloPatolli.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCasillas)
                                    .addComponent(lblFichas)
                                    .addComponent(lblJugadores)
                                    .addComponent(lblFichas1)
                                    .addComponent(lblFichas2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboFichas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboAspas, 0, 135, Short.MAX_VALUE)
                            .addComponent(comboJugadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContinuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFondo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(78, 78, 78)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadores)
                    .addComponent(comboJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasillas)
                    .addComponent(comboAspas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFichas))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFichas1)
                    .addComponent(txtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFichas2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJugadoresActionPerformed

    private void comboAspasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAspasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAspasActionPerformed

    private void comboFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFichasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFichasActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        GuiPrincipal principal = new GuiPrincipal(control);
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        
        Partida p = new Partida();
        p.setApuesta(Integer.parseInt(this.txtMonto.getText()));
        p.setNumFichas(Integer.parseInt(this.comboFichas.getSelectedItem().toString()));
        p.setNumJugadores((Integer.parseInt(this.comboJugadores.getSelectedItem().toString())));
        p.setNumAspas(Integer.parseInt(this.comboAspas.getSelectedItem().toString()));
        System.out.println(p);
        this.control.enviar(new ProtocoloMensaje("CONFIGURARJUEGO",p));
        
        GuiConfigurarJugador configurarJugador = new GuiConfigurarJugador(control);
        configurarJugador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnContinuarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> comboAspas;
    private javax.swing.JComboBox<String> comboFichas;
    private javax.swing.JComboBox<String> comboJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCasillas;
    private javax.swing.JLabel lblFichas;
    private javax.swing.JLabel lblFichas1;
    private javax.swing.JLabel lblFichas2;
    private javax.swing.JLabel lblJugadores;
    private javax.swing.JTextField txtFondo;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
